// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rsf.Database;

namespace rsf.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class DefaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("rsf.Models.AccountModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Banned");

                    b.Property<DateTime>("BeginBannedTime");

                    b.Property<string>("Email");

                    b.Property<DateTime>("EndBannedTime");

                    b.Property<string>("ForumName");

                    b.Property<string>("IP");

                    b.Property<int>("MaxCharacters");

                    b.Property<string>("Password");

                    b.Property<int>("PermBanned");

                    b.Property<int>("RoleID");

                    b.Property<string>("SocialClubName");

                    b.Property<string>("TeamSpeakUniqueID");

                    b.Property<string>("Username");

                    b.Property<int>("WhiteListed");

                    b.HasKey("UserID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("rsf.Models.CharacterModel", b =>
                {
                    b.Property<int>("CharID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountBalance");

                    b.Property<double>("Bank");

                    b.Property<int>("Dead");

                    b.Property<int>("Jail");

                    b.Property<int>("Jailtime");

                    b.Property<int>("JobID");

                    b.Property<int>("JobRank");

                    b.Property<double>("Money");

                    b.Property<string>("NachName");

                    b.Property<int>("RoleID");

                    b.Property<int>("Sex");

                    b.Property<int>("UserID");

                    b.Property<string>("VorName");

                    b.Property<int>("WJobID");

                    b.Property<int>("Wantedlevel");

                    b.Property<int>("onDuty");

                    b.HasKey("CharID");

                    b.HasIndex("UserID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("rsf.Models.CharacterModel", b =>
                {
                    b.HasOne("rsf.Models.AccountModel")
                        .WithMany("Characters")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
